@startuml
autonumber
'hide footbox
actor "User" as user

participant ":System" as sys

activate user

user -> sys: Asks to see te passages between 2 Buildings 
activate sys

alt successful case
    sys --> user: show the passage
else
    sys --> user: show failure message
end
deactivate sys
@enduml
