@startuml
autonumber
'hide footbox
actor "Admin" as admin

participant ":System" as sys
participant ":API create passages" as floor

activate admin

admin -> sys: create passages
activate sys

sys --> admin: request necessary data()
admin -> sys : insert all the data
activate floor
sys -> floor: Post route{id, passages}

alt successful case
    floor --> sys: HTTP: 201
    sys --> admin: show success message
else
    floor --> sys: HTTP: 400
    sys --> admin: show failure message
end
deactivate floor
deactivate sys
@enduml