@startuml
autonumber
'hide footbox
actor "Admin" as admin

participant ":System" as sys
participant ":Robot" as robot

activate admin

admin -> sys: create a Route
activate sys

sys --> admin: request necessary data()
admin -> sys : insert all the data
activate robot
sys -> robot: POST route{id, nickname, robotType, serialNumber, description}

alt successful case
    robot --> sys: HTTP: 201
    sys --> admin: show success message
else
    robot --> sys: HTTP: 400
    sys --> admin: show failure message
end
deactivate robot
deactivate sys
@enduml